### PR TITLE
Multi *Arr Instance Support , Add Serilog for better logging, Add Fluent Validator

### PR DESCRIPTION
**Pull request by xpsony**
Now it is possible to use multiple instances of the *arr applications with UmlautAdaptarr.

Nothing changes for existing users. The variables for a single Instance remain the same.

Only if you want to add another instance, you have to adapt the existing instance.

--------
Example using 2 Sonarr applications :

**Note the Name Variabel is only Optional , If no name is stored.  the url of the instance is the name**

The first instance starts at 0

- Sonarr__0__Enabled: true (set to false to disable)
- Sonarr__0__Name: Name of the Instance (Optional)
- Sonarr__0__Host: your_sonarr_host_url
- Sonarr__0__ApiKey: your_sonarr_api_key

The 2nd instance would then be index 1

- Sonarr__1__Enabled: true (set to false to disable)
- Sonarr__1__Name: Name of the Instance (Optional)
- Sonarr__1__Host: your_sonarr_host_url
- Sonarr__1__ApiKey: your_sonarr_api_key

etc.

--------
- Serilog extension for better logging
- Instance name is now displayed in the log
- Extension with Fluent Validator to check the config before starting
- Cleanup some code

### CODE REVIEW

**Comment by xpsony** [comment]
**Note : Tested only with Sonnar, because i have no Readarr or Lidarr**

**Comment by xpsony** [comment]
Docker Image for testing : [lexfi/umlautadaptarr:latest](https://hub.docker.com/repository/docker/lexfi/umlautadaptarr/tags)

**Comment by xpsony** [comment]
+ Fix Problem with BeReachable Test at Startup
+ Add "Ip Leak Test" , so User can see at Startup what Public Ip Address  the Docker is using

**Comment by PCJones** [comment]
ETA 2-10 weeks, then I'll have the time to approve this! Thanks for your patience :)

**Pull request merged**
